version: '3'
services:
  web:
    build: .
    command: 'yarn start:docker:local'
    environment:
      NODE_ENV: local
    ports:
      - "4000:4000"
    links:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password2'
      MYSQL_DATABASE: 'books-app'
      MYSQL_USER: 'book-user'
      MYSQL_PASSWORD: 'password1'
      DATABASE_HOST: sql
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/filess/:/data_backup/data
  # db:
  #   image: mysql:5.7.13
  #   command: --max_connections=2213 --max_allowed_packet=1G --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'password2'
  #     MYSQL_DATABASE: 'books-app'
  #     MYSQL_USER: 'book-user'
  #     MYSQL_PASSWORD: 'password1'
  #     DATABASE_HOST: sql
  #     MYSQL_ROOT_HOST: '%'
  #   networks:
  #     - app-network
  #   expose:
  #     - "3306"
  #   ports:
  #     - "3306:3306"
  #   restart: always
  #   volumes:
  #     - "./.mysql/5.7.13-data/db:/var/lib/mysql5.7.13"
  #     - ./mysql5.7.13/my.cnf

volumes: 
  db-config:
  db-data: